app/blueprints/social/models.py
from datetime import datetime
import secrets 
import uuid
from werkzeug.security import check_password_hash, generate_password_hash

from app import db, login
from flask_login import UserMixin

@login.user_loader
def load_user(id):
    return User.query.get(int(id))

class User(UserMixin, db.Model):
    id = db.Column(db.Integer, primary_key=True)
    username = db.Column(db.String(64),index=True,unique=True)
    email = db.Column(db.String(100),index=True,unique=True)
    password_hash = db.Column(db.String(128))
    token = db.Column(db.String, unique= True)
    posts = db.relationship('Post', backref='author',lazy='dynamic')

    def __repr__(self):
        return f'User {self.username}'
    
    def set_token(self):
        setattr(self,'token',secrets.token_urlsafe(32))
        

    def set_id(self):
        return str(uuid.uuid4())
    
    def hash_password(self, password):
        self.password_hash = generate_password_hash(password)

    def check_password(self, password):
        return check_password_hash(self.password_hash, password)
    
    def commit(self):
        db.session.add(self)
        db.session.commit()
        
class Post(db.Model):
    id = db.Column(db.Integer, primary_key=True)
    body = db.Column(db.String(140))
    timestamp = db.Column(db.DateTime, default=datetime.utcnow)
    user_id = db.Column(db.Integer, db.ForeignKey('user.id'))

    def __repr__(self) -> str:
        return f'Post by {self.author.username}: {self.body}'
    
    def commit(self):
        db.session.add(self)
        db.session.commit()

app/forms.py
from flask_wtf import FlaskForm
from wtforms import StringField, PasswordField, SubmitField
from wtforms.validators import DataRequired, EqualTo

class RegisterForm(FlaskForm):
    username = StringField('Username', validators=[DataRequired()])
    email = StringField('email', validators=[DataRequired()])
    password = PasswordField('Password', validators=[DataRequired()])
    confirm_password = PasswordField('Confirm Password', validators=[DataRequired(), EqualTo('password', message="Passwords must Match!")])
    submit = SubmitField('Register')

class SignInForm(FlaskForm):
    username = StringField('Username', validators=[DataRequired()])
    password = PasswordField('Password', validators=[DataRequired()])
    submit = SubmitField('Sign In')

class PostForm(FlaskForm):
    body = StringField('Body', validators=[DataRequired()])
    submit = SubmitField('Post')

class SearchForm(FlaskForm):
    username = StringField('Username', validators=[DataRequired()])
    submit = SubmitField('Seach User')

app/__init__.py
from flask import Flask
from flask_cors import CORS
from config import Config
from flask_sqlalchemy import SQLAlchemy
from flask_migrate import Migrate
from flask_login import LoginManager

app = Flask(__name__)
CORS(app)
app.config.from_object(Config)
db = SQLAlchemy(app)
migrate = Migrate(app, db)
login = LoginManager(app)

from app.blueprints.main import bp as main_bp
app.register_blueprint(main_bp)
from app.blueprints.auth import bp as auth_bp
app.register_blueprint(auth_bp)
from app.blueprints.social import bp as social_bp
app.register_blueprint(social_bp)
from app.blueprints.api import bp as api_bp
app.register_blueprint(api_bp)

app/blueprints/api/__init__.py
from flask import Blueprint

bp = Blueprint('api', __name__, url_prefix='/api')

from app.blueprints.api import routes, auth_routes

app/blueprints/api/routes.py
from . import bp as app
from app.blueprints.social.models import Post, User
from flask import make_response, request

@app.route('/posts')
def api_posts():
    result = []
    for post in Post.query.all():
        result.append({
            'id': post.id,
            'body': post.body,
            'date_created': post.timestamp,
            'username': post.author.username
        })

    return result

@app.route('/user-posts/<user>')
def user_posts(user):
    print('test')
    result = []
    user_match = User.query.filter_by(username=user).first()
    if not user_match:
        return make_response('User not Found', 404)
    content = request.headers.get('Authorization')
    print(content)
    print(user_match.token == 'test' )
    user_posts = user_match.posts
    for post in user_posts:
        result.append({
            'id': post.id,
            'body': post.body,
            'date_created': post.timestamp,
            'username': post.author.username
        })

    return result

@app.route('/post/<id>')
def api_post_by_id(id):
    post = Post.query.get(int(id))
    if not post:
        return make_response('Post not Found', 404)
    return {
            'id': post.id,
            'body': post.body,
            'date_created': post.timestamp,
            'username': post.author.username
        }

@app.post('/post/<uid>')
def post_post(uid):
    # WE know the Id already its from the g.current_user
    # I needa body still!??!!?!
    posted_data = request.get_json()
    post = Post(user_id = uid.current_user.id, body = posted_data["body"])
    post.save()
    return make_response('success', 200)

app/blueprints/main/__init__.py
from flask import Blueprint

bp = Blueprint('main', __name__)

from app.blueprints.main import routes

app/blueprints/main/routes.py
from . import bp as app
from flask import Flask, render_template, g

@app.route('/')
def index():
    cdn={
        'instructors':('lucas','dylan'),
        'students':['blane','ashmika','abe','zi','connor','martin','noah','erm']
    }
    return render_template('index.jinja', cdn=cdn, title='Home',search_form=g.search_form, post_form=g.post_form)

@app.route('/about')
def about():
    return render_template('about.jinja',search_form=g.search_form, post_form=g.post_form)

app/blueprints/social/__init__.py
from flask import Blueprint

bp = Blueprint('social', __name__)

from app.blueprints.social import routes

app/blueprints/social/routes.py
from . import bp as social_bp 
from app.blueprints.social.models import User, Post
from app.forms import PostForm, SearchForm
from flask import redirect, render_template, url_for, flash, g
from flask_login import login_required, current_user
from app import app

@app.before_request
def before_request():
    g.post_form = PostForm()
    g.search_form = SearchForm()

@social_bp.route('/user/<username>')
def user(username):
    user_match = User.query.filter_by(username=username).first()
    if not user_match:
        flash(f'User {username} doesn\'t exit')
        return redirect(url_for('main.index'))
    posts = user_match.posts
    return render_template('user.jinja', user=user_match, posts=posts, search_form=g.search_form, post_form=g.post_form)


@social_bp.post('/post')
@login_required
def post():
    if g.post_form.validate_on_submit():
        body = g.post_form.body.data
        p = Post(body=body, user_id=current_user.id)
        p.commit()
        return redirect(url_for('social.user', username=current_user.username))
    return redirect(url_for('main.index'))
    
@social_bp.post('/search')
def user_search():
    if g.search_form.validate_on_submit():
        return redirect(url_for('social.user',username=g.search_form.username.data))
    return redirect(url_for('main.index'))

app/templates/about.jinja
{% extends 'base.jinja' %}

{% block content %}
    <h2>About Page</h2>
{% endblock %}

app/templates/base.jinja
<!DOCTYPE html>
<html lang="en" data-bs-theme="dark">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="{{ url_for('static', filename='main.css')}}">
    {% if title %}
    <title>{{ title }} - Fakebook</title>
    {% else %}
    <title>Welcome to FakeBook</title>
    {% endif %}
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-GLhlTQ8iRABdZLl6O3oVMWSktQOp6b7In1Zl3/Jr59b6EGGoI1aFkw7cmDA6j6gD" crossorigin="anonymous">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha1/dist/js/bootstrap.bundle.min.js" integrity="sha384-w76AqPfDkMBDXo30jS1Sgez6pr3x5MlQ1ZAGC+nuZB+EYdgRZgiwxhTBTkF7CXvN" crossorigin="anonymous"></script>
</head>

<body>
    <main class="container mt-1">
        {% include 'navbar.jinja' %}
        {% with messages = get_flashed_messages() %}
        {% if messages %}
        <ul>
            {% for message in messages %}
                <li> {{ message }} </li>
            {% endfor %}
        </ul>
        {% endif %}
        {% endwith %}
        {% if current_user.is_authenticated %}
        <div class="row">
            <div class="col-6">{% include './includes/post.jinja' %}</div>
            <div class="col-6">{% include './includes/search.jinja' %}</div>
        </div>
        {% endif %}
        <h1>FakeBook CDN - Changes</h1>
        {% block content %}

        {% endblock %}
    </main>
</body>
</html>

app/templates/includes/post.jinja
<form action="{{ url_for('social.post')}}" method="post">
    {{ post_form.hidden_tag() }}
    <p>
        {{ post_form.body.label }}<br>
        {{ post_form.body(size=32) }}
    </p>
    
    <p>
        {{ post_form.submit(class='btn btn-primary') }}
    </p>
</form>

app/templates/includes/search.jinja
<form action="{{ url_for('social.user_search')}}" method="post">
    {{ search_form.hidden_tag() }}
    <p>
        {{ search_form.username.label }}<br>
        {{ search_form.username(size=32) }}
    </p>
    
    <p>
        {{ search_form.submit(class='btn btn-primary') }}
    </p>

</form>

app/templates/index.jinja
{% extends 'base.jinja' %}

{% block content %}
    <h2>CDN 109</h2>
    <h2>Instructors</h2>
    {% for instructor in cdn['instructors'] %}
        <span>{{ instructor }} </span>
    {% endfor %}
    <h2>Students</h2>
    {% for student in cdn.students %}
        <p>{{ student }}</p>
    {% endfor %}
{% endblock %}

app/templates/navbar.jinja
<nav class="navbar navbar-expand-lg bg-body-tertiary">
  <div class="container-fluid">
    <a class="navbar-brand" href="/">CDN Fakebook</a>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNavAltMarkup" aria-controls="navbarNavAltMarkup" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarNavAltMarkup">
      <div class="navbar-nav">
        <a class="nav-link active" aria-current="page" href="/">Home</a>
        <a class="nav-link" href="{{ url_for('main.about') }}">About</a>
        {% if current_user.is_anonymous %}
        <a class="nav-link" href="{{ url_for('auth.sign_in') }}">Sign In</a>
        <a class="nav-link" href="{{ url_for('auth.register')}}">Register</a>
        {% else %}
        <a class="nav-link" href="{{ url_for('auth.log_out')}}">Logout</a>
        {% endif %}
      </div>
    </div>
  </div>
</nav>

app/templates/register.jinja
{% extends "base.jinja" %}

{% block content %}
    <h2>Register</h2>
    <form action="" method="post">
        {{ form.hidden_tag() }}
        <p>
            {{ form.username.label }}<br>
            {{ form.username(size=32) }}
            {% for error in form.username.errors %}
            <span>{{ error }}</span>
            {% endfor %}
        </p>
        <p>
            {{ form.email.label }}<br>
            {{ form.email(size=32) }}
            {% for error in form.email.errors %}
            <span>{{ error }}</span>
            {% endfor %}
        </p>
        <p>
            {{ form.password.label }}<br>
            {{ form.password(size=32) }}
            {% for error in form.password.errors %}
            <span>{{ error }}</span>
            {% endfor %}
        </p>
        <p>
            {{ form.confirm_password.label }}<br>
            {{ form.confirm_password(size=32) }}
            {% for error in form.confirm_password.errors %}
            <span>{{ error }}</span>
            {% endfor %}
        </p>
        <p>{{ form.submit(class='btn btn-primary') }}</p>
    </form>
{% endblock %}

app/templates/signin.jinja
{% extends "base.jinja" %}

{% block content %}
<h2>Sign In</h2>
    <form action="" method="post">
        {{ sign_in_form.hidden_tag() }}
        <p>
            {{ sign_in_form.username.label }}<br>
            {{ sign_in_form.username(size=32) }}
        </p>
        <p>
            {{ sign_in_form.password.label }}<br>
            {{ sign_in_form.password(size=32) }}
        </p>
        <p>
            {{ sign_in_form.submit(class='btn btn-primary') }}
        </p>

    </form>
{% endblock %}

app/templates/user.jinja
{% extends "base.jinja" %}

{% block content %}
    <h2>{{ user.username }}'s Profile</h2>
    <h3>Posts</h3>
    {% for post in user.posts %}
        <p>{{ post }}</p>
    {% endfor %}
{% endblock %}